apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: {{ .Values.name }}
spec:
    selector:
        matchLabels:
            app: {{ .Values.name }}
    replicas: {{ .Values.replicaCount }}
    template:
        metadata:
            labels:
                app: {{ .Values.name }}
        spec:
            containers:
              - name: {{ .Values.App.name }}
                image: {{ .Values.App.image }}
                imagePullPolicy: {{ .Values.App.imagePullPolicy }}
                ports:
                  - name: http
                    containerPort: {{ .Values.App.http_port }}
              - name: {{ .Values.Consul.name }}
                image: {{ .Values.Consul.image }}
                ports:
                  - name: http
                    containerPort: {{ .Values.Consul.http_port }}